# Generated by Django 5.1.5 on 2025-02-02 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=150, verbose_name='Familiya')),
                ('image', models.ImageField(default='authors/default.png', upload_to='avatars/', verbose_name='Rasmi')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Nomi')),
                ('description', models.TextField(verbose_name='Haqida')),
                ('image', models.ImageField(default='books/default.png', upload_to='books/', verbose_name='Rasmi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author', verbose_name='Yozuvchi')),
            ],
        ),
    ]
