# Generated by Django 5.1.5 on 2025-02-02 10:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Chiqarilgan sana'),
            preserve_default=False,
        ),
    ]
