# Generated by Django 5.1.5 on 2025-02-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_book_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(default=0, verbose_name='Sahifalar soni'),
        ),
    ]
